version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - echo "Running pre-build steps..."
  build:
    commands:
      - echo "Compiling the source..."
      - npm install
      - cdk deploy --require-approval never
  post_build:
    commands:
      - echo "Build completed"