version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing the AWS CDK CLI..."
      - npm install -g aws-cdk
      - echo "Installing the dependencies..."
      - npm install
      - echo "Installing the testing dependencies..."
      - npm install --save-dev jest @aws-cdk/assertions
  pre_build:
    commands:
      - echo "Running unit tests..."
      - npm test
  build:
    commands:
      - echo "Compiling the source..."
      - cdk synth WebCrawlerStack --json > WebCrawlerStack.json
  post_build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - WebCrawlerStack.json
